/* ═══════════════════════════════════════════════════════════════
   ClubCampus — shared/componentRegistry.js
   Alle wiederverwendbaren UI-Komponenten
   ═══════════════════════════════════════════════════════════════ */

export const COMPONENT_REGISTRY = [
  {
    name: "Toolbar",
    desc: "Suche, Filter, Gruppieren, Mehr-Menu, Spaltenauswahl. Wird in allen Listen-Modulen verwendet.",
    category: "Listen",
    usedIn: ["MitgliederModul", "KaderModul", "HelferModul"],
    props: ["search+onSearch", "filterDefs+filterVals+onFilterChange", "groupOptions+groupBy+onGroupChange", "colMenu", "moreItems"],
    css: ["cc-filter-search", "cc-filter-sec-hdr", "cc-filter-sec-name", "cc-filter-sec-badge", "cc-filter-sec-body", "cc-ml-chip", "cc-ml-chips", "cc-ml-chip-x"],
  },
  {
    name: "RangeFilter",
    desc: "Zahlen-Range-Filter mit zwei Slidern + editierbaren Inputs (von/bis). Wird in Toolbar filterDefs mit type:'range' verwendet.",
    category: "Formulare",
    usedIn: ["MitgliederModul"],
    props: ["min", "max", "suffix", "rv", "rangeKey", "onFilterChange", "padLeft"],
    css: ["cc-range-slider"],
  },
  {
    name: "ColMenuButton",
    desc: "Spaltenauswahl mit Drag&Drop und Suche. Immer zusammen mit Toolbar verwendet.",
    category: "Listen",
    usedIn: ["MitgliederModul"],
    props: ["allCols", "visibleCols", "onChangeVisible"],
  },
  {
    name: "BulkBar",
    desc: "Aktionsleiste für Mehrfachauswahl. Erscheint wenn Zeilen selektiert sind.",
    category: "Listen",
    usedIn: ["MitgliederModul"],
    props: ["count", "onClear", "actions[]"],
  },
  {
    name: "SortHeader",
    desc: "Sortierbarer Tabellen-Header mit Pfeil-Indikator.",
    category: "Listen",
    usedIn: ["MitgliederModul", "KaderModul"],
    props: ["label", "col", "sortCol", "sortDir", "onSort"],
  },
  {
    name: "DropMenu",
    desc: "Kontext-Menu mit Items. Auf Mobile automatisch Bottom Sheet.",
    category: "Navigation",
    usedIn: ["MitgliederModul", "KaderModul", "PortalverwaltungModul"],
    props: ["items[]", "trigger"],
  },
  {
    name: "ModalOrSheet",
    desc: "Modal auf Desktop, Bottom Sheet auf Mobile. Immer verwenden statt eigenem Modal.",
    category: "Overlays",
    usedIn: ["MitgliederModul", "ElternTab", "KaderModul"],
    props: ["open", "onClose", "title", "maxWidth"],
  },
  {
    name: "ConfirmDialog + useConfirm",
    desc: "Ersetzt window.confirm(). Hook gibt [confirm, dialog] zurück. confirmDialog ins JSX rendern.",
    category: "Overlays",
    usedIn: ["MitgliederModul", "PortalverwaltungModul", "TrainingsplanModul"],
    props: ["useConfirm() → [confirm, confirmDialog]", "confirm({title, message, confirmLabel})"],
  },
  {
    name: "InfoBox",
    desc: "Farbiger Hinweiskasten. Farbe via color prop (BL=Info, GN=Erfolg, AM=Warnung, R=Fehler).",
    category: "Feedback",
    usedIn: ["Überall"],
    props: ["text", "color"],
  },
  {
    name: "StatusTile",
    desc: "Status-Kachel mit Icon, Label und Wert. Für Profil-Übersichten.",
    category: "Feedback",
    usedIn: ["MemberDetail", "DashboardModul"],
    props: ["label", "value", "icon", "semantic (ok|warn|danger|neutral)", "action"],
  },
  {
    name: "Btn",
    desc: "Primär-Button mit Vereinsfarbe. Für Sekundär-Aktionen cc-btn-outline verwenden.",
    category: "Basics",
    usedIn: ["Überall"],
    props: ["onClick", "color", "textColor", "small", "disabled"],
  },
  {
    name: "Card",
    desc: "Weisser Container mit Border und Schatten.",
    category: "Basics",
    usedIn: ["Überall"],
    props: ["mb", "mt", "flush", "onClick"],
  },
  {
    name: "Chip",
    desc: "Farbiger Badge. text-Prop für Label, color für Textfarbe, bg für Hintergrund.",
    category: "Basics",
    usedIn: ["Überall"],
    props: ["text", "color", "bg", "semantic", "size"],
  },
  {
    name: "Stat",
    desc: "Statistik-Kachel mit Label, Wert und optionaler Farbe.",
    category: "Basics",
    usedIn: ["DashboardModul", "PortalverwaltungModul"],
    props: ["label", "value", "sub", "color", "semantic", "icon"],
  },
  {
    name: "Av",
    desc: "Avatar mit Initialen und automatischer Farbzuweisung aus Name-Hash.",
    category: "Basics",
    usedIn: ["Überall"],
    props: ["name", "size (sm|md|lg oder px-Zahl)", "bg"],
  },
  {
    name: "Tabs",
    desc: "Tab-Navigation. Für Segment-Control cc-seg/cc-seg-item/cc-seg-active verwenden.",
    category: "Navigation",
    usedIn: ["MemberDetail", "KaderModul"],
    props: ["tabs[] (key+label)", "active", "setActive", "mb"],
  },
  {
    name: "Row / Col / Between",
    desc: "Layout-Helfer. Row=horizontal, Col=vertikal, Between=space-between.",
    category: "Layout",
    usedIn: ["Überall"],
    props: ["gap", "wrap", "justify", "align", "style"],
  },
  {
    name: "H1 / H2 / STitle / Sub / Label",
    desc: "Typografie-Komponenten. STitle für Section-Überschriften, Sub für sekundären Text.",
    category: "Layout",
    usedIn: ["Überall"],
    props: ["children", "mb", "style"],
  },
  {
    name: "Input / Select / Textarea",
    desc: "Formular-Elemente mit cc-input Styling.",
    category: "Formulare",
    usedIn: ["Überall"],
    props: ["Standard HTML props + style"],
  },
  {
    name: "Empty",
    desc: "Leer-Zustand mit Icon und Text.",
    category: "Feedback",
    usedIn: ["Überall"],
    props: ["icon", "text", "sub"],
  },
  {
    name: "FunktionenMultiSelect",
    desc: "Multi-Select für Vereinsfunktionen mit Suche und Gruppenfilter.",
    category: "Formulare",
    usedIn: ["MitgliederModul", "GruppenTab"],
    props: ["funktionen[]", "selected[]", "onChange"],
  },
  {
    name: "useAddrSearch",
    desc: "Hook: Adress-Autocomplete via swisstopo API. Gibt Vorschläge für Strasse+PLZ+Ort zurück.",
    category: "Formulare",
    usedIn: ["PersonKontakt", "NeuesMitgliedModal"],
    props: ["strasse", "plz"],
  },
  {
    name: "RollenAuswahlListe",
    desc: "Shared Rollenauswahl mit Suche, Checkboxen und Trainer-Badge. Für PersonTeams und KaderModul.",
    category: "Formulare",
    usedIn: ["PersonTeams"],
    props: ["rollen", "selected", "onChange", "search", "onSearchChange"],
  },
  {
    name: "PhoneInput",
    desc: "Telefonnummer-Eingabe mit Ländervorwahl-Dropdown, automatischer Formatierung und Validierung.",
    category: "Formulare",
    usedIn: ["PersonKontakt", "NeuesMitgliedModal"],
    props: ["value", "onChange", "placeholder", "showHint", "className"],
  },
  {
    name: "LandSelect",
    desc: "Länder-Auswahl mit Flaggen und Suche.",
    category: "Formulare",
    usedIn: ["MitgliederModul"],
    props: ["value", "onChange", "laender[]", "placeholder"],
  },
];
